### PR TITLE
helm za infrastrukturu

### PR DESCRIPTION
**Pull request by VeljkoZivanovic**

### CODE REVIEW

**Comment by ghost** [comment]
LGTM label has been added.  <details>Git tree hash: 81473534bdd28dfc7b2c1eb368101f96387d2ba9</details>

**Review by CommandLineFox — APPROVED** [review]
Aladeen odrađeno

/approve

**Review by CommandLineFox — APPROVED** [review]
Aladeen odrađeno br 2

/approve

**Pull request merged**
